#!/bin/bash
ssh root@192.168.1.3 ' df -i ' > /root/Desktop/inode
a=$(cat /root/Desktop/inode | awk '{sum+=$5} END {print sum}')
echo "Dung luong cua o dia la"
echo $a
if [ $a -gt 1 ]
then
	echo "Dung luong o dia gan day" | mail -s "Dung luong" root@localhost.localdomain
fi

