#!/bin/bash
ssh root@192.168.1.3 ' ps -eo pcpu ' > /root/Desktop/pcpu.txt
ssh root@192.168.1.3 ' ps -eo pmem ' > /root/Desktop/pmem.txt
a=$(cat /root/Desktop/pcpu.txt | tail -n+2 | awk '{sum+=$1} END {print sum}')
b=$(cat /root/Desktop/pmem.txt | tail -n+2 | awk '{mem+=$1} END {print mem}')
echo "% CPU da cung : $a"
echo "% MEM da dung : $b"
if [[ $a > 10.0 ]]
then
	echo "CPU qua tai" | mail -s "CPU" root@localhost.localdomain
	echo "Da gui mail"
fi
