#!/bin/bash
ssh root@192.168.1.4 ' ps -eo pcpu | tail -n+2 ' > /root/Desktop/a
cpu=`cat a | awk '{sum+=$1} END {print sum}'`
echo "%cpu la : $cpu"
if [[ $cpu > 40.0 ]]
then
echo "CPU vuot qua 40%" | mail -s "CPU" root@localhost.localdomain
echo "Da gui mail cho server"
fi
