#!/bin/bash
rm -f /root/Desktop/Sizeuser
userID=$(cat /etc/passwd |  awk -F ":" '{print $3}')
for i in $userID
do
	if [ $i -gt 499 -a $i -lt 65534 ]
	then
		user=$(grep $i /etc/passwd | awk -F ":" '{print $1}')
		echo $user		
		for j in $user
		do
			size=$(find / -user $j 2> /dev/null -type f -exec stat --format %s '{}' \; | awk '{sum+=$1}END{print sum}')
			echo "$j	$size" >> /root/Desktop/Sizeuser
		done
	fi
done
while read line
do
	name=$(echo $line | awk '{print $1}')
	dungluong=$(echo $line | awk '{print $2}')
	ve=$(($dungluong/1024))
	echo "$ve KB"
	echo -ne "[$name] :\t"
	for k in $(seq 1 $ve)
	do
		echo -n "#" 
	done
	echo " "
done < /root/Desktop/Sizeuser
